language: python
env:
     - REPO=google/packet-queue
     - REPO=google/pandas
     # - REPO=google/paramgmt  # No problems found
     - REPO=google/personfinder
     - REPO=google/pinject
     # - REPO=google/prettytensor  # No problems found
     - REPO=google/protobuf
     - REPO=google/protocall
     - REPO=google/protorpc
     - REPO=google/py-ast-utils
     - REPO=google/py-html-contextual-escaping
     - REPO=google/pygtrie
     - REPO=google/pyringe
     - REPO=google/python_portpicker
     - REPO=google/python-adb
     - REPO=google/python-atfork
     - REPO=google/python-cloud-utils
     - REPO=google/python-fire
     - REPO=google/python-gflags
     - REPO=google/python-subprocess32
     - REPO=google/pytruth
     - REPO=google/pytype
     - REPO=google/pytypedecl
     - REPO=google/pyu2f
     - REPO=google/pywebsocket
     - REPO=google/realtime-help
     - REPO=google/rekall
     - REPO=google/request-test
     - REPO=google/resolver-library
     - REPO=google/rfmt
     - REPO=google/roboto
     - REPO=google/rtc-video-quality
     - REPO=google/rttcp
     - REPO=google/sanitizers
     # - REPO=google/seq2seq  # No problems found
     - REPO=google/shipshape-demo
     - REPO=google/simian
     - REPO=google/simple-reinforcement-learning
     - REPO=google/smilesparser
     - REPO=google/spatial-media
     - REPO=google/sprockets
     - REPO=google/squires
     - REPO=google/sre_yield
     - REPO=google/ssl_logger
     # - REPO=google/streetview-publish-client-libraries  # No problems found
     - REPO=google/stress_transfer
     - REPO=google/subpar
     - REPO=google/support-tools
     - REPO=google/tcp_killer
     - REPO=google/terminal-app-function-keys
     - REPO=google/terminal-py
     - REPO=google/text2text
     - REPO=google/textfsm
     - REPO=google/timesketch
     - REPO=google/transitfeed
     - REPO=google/turbinia
     - REPO=google/url_diff
     - REPO=google/usbinfo
     - REPO=google/vimdoc
     - REPO=google/vogon
     - REPO=google/vroom
     - REPO=google/wheelbarrow
     - REPO=google/winops
     - REPO=google/x509test
     - REPO=google/yapf
     # - REPO=google/youtube-8m  # No problems found
     # - REPO=google/Zhi  # No problems found
     - REPO=googlei18n/noto-emoji
python:
    - 2.7.13
    - 3.6
install:
    - pip install hacking  # pytest  # add other testing frameworks later
before_script:
    - URL=https://github.com/${REPO}
    - echo ; echo -n "flake8 testing of ${URL} on " ; python -V
    - git clone --depth=50 --branch=master ${URL} ~/${REPO}
    - cd ~/${REPO}
script:
    - echo stop the build if there are Python syntax errors or undefined names
    - echo ; echo -n "flake8 testing of ${URL} on " ; python -V
    - time flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
    - echo exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
    - time flake8 . --count --exit-zero --ignore=E111 --max-complexity=10 --max-line-length=127 --statistics
notifications:
    on_success: change
    on_failure: change  # `always` will be the setting once code changes slow down
