language: python
env:
     - REPO=googlefonts/fontbakery
     - REPO=googlefonts/gf-glyphs-scripts
     - REPO=googlefonts/rubik
     - REPO=googlefonts/robotoslab
     - REPO=googlefonts/fontbakery-dashboard
     - REPO=googlefonts/MooniakFontsGFVersion
     - REPO=googlefonts/MuktaGFVersion
     - REPO=googlefonts/SourceSerifProGFVersion
     - REPO=googlefonts/FiraGFVersion
     - REPO=googlefonts/LatoGFVersion
     - REPO=googlefonts/Work-Sans
     - REPO=googlefonts/fontcrunch
     - REPO=googlefonts/namecheck     - REPO=googlei18n/noto-emoji
python:
    - 2.7.13
    - 3.6
install:
    - pip install hacking  # pytest  # add other testing frameworks later
before_script:
    - URL=https://github.com/${REPO}
    - echo ; echo -n "flake8 testing of ${URL} on " ; python -V
    - git clone --depth=50 --branch=master ${URL} ~/${REPO}
    - cd ~/${REPO}
script:
    - echo stop the build if there are Python syntax errors or undefined names
    - echo ; echo -n "flake8 testing of ${URL} on " ; python -V
    - time flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
    - echo exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
    - time flake8 . --count --exit-zero --ignore=E111 --max-complexity=10 --max-line-length=127 --statistics
notifications:
    on_success: change
    on_failure: change  # `always` will be the setting once code changes slow down
