language: python
env:
     #- REPO=googlefonts/fontbakery
     #- REPO=googlefonts/gf-glyphs-scripts
     #- REPO=googlefonts/rubik
     ## - REPO=googlefonts/robotoslab
     #- REPO=googlefonts/fontbakery-dashboard
     #- REPO=googlefonts/MooniakFontsGFVersion
     #- REPO=googlefonts/MuktaGFVersion
     #- REPO=googlefonts/SourceSerifProGFVersion
     #- REPO=googlefonts/FiraGFVersion
     #- REPO=googlefonts/LatoGFVersion
     ## - REPO=googlefonts/Work-Sans
     ## - REPO=googlefonts/fontcrunch
     #- REPO=googlefonts/namecheck
     #- REPO=googlei18n/noto-emoji
    - REPO=google/OctoPrint-LEDStripControl
    - REPO=google/aiyprojects-raspbian  # has .travis.yml file
    - REPO=google/apitools  # has .travis.yml file
    - REPO=google/bazel-common
    - REPO=google/budou  # has .travis.yml file
    - REPO=google/cauliflowervest  # has .travis.yml file
    - REPO=google/cel-spec  # has .travis.yml file
    - REPO=google/ci_edit
    - REPO=google/containerregistry  # has .travis.yml file
    - REPO=google/ctfscoreboard  # has .travis.yml file
    - REPO=google/ggrc-core
    - REPO=google/google-api-python-client  # has .travis.yml file
    - REPO=google/google-reauth-python  # has .travis.yml file
    - REPO=google/grr  # has .travis.yml file
    - REPO=google/import-mailbox-to-gmail
    - REPO=google/importlab
    - REPO=google/loaner
    - REPO=google/makerfaire-booth
    - REPO=google/mobly  # has .travis.yml file
    - REPO=google/mozc-devices
    - REPO=google/nsscache  # has .travis.yml file
    - REPO=google/nucleus
    - REPO=google/pasta  # has .travis.yml file
    - REPO=google/python-adb  # has .travis.yml file
    - REPO=google/python-cloud-utils
    - REPO=google/pytype
    - REPO=google/rekall
    - REPO=google/timesketch  # has .travis.yml file
    - REPO=google/transitfeed  # has .travis.yml file
    - REPO=google/yapf  # has .travis.yml file
python:
    - 2.7.13
    - 3.6
install:
    - pip install hacking  # pytest  # add other testing frameworks later
before_script:
    - URL=https://github.com/${REPO}
    - echo ; echo -n "flake8 testing of ${URL} on " ; python -V
    - git clone --depth=50 --branch=master ${URL} ~/${REPO}
    - cd ~/${REPO}
script:
    - echo stop the build if there are Python syntax errors or undefined names
    - echo ; echo -n "flake8 testing of ${URL} on " ; python -V
    - time flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
    - echo exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
    - time flake8 . --count --exit-zero --ignore=E111 --max-complexity=10 --max-line-length=127 --statistics
notifications:
    on_success: change
    on_failure: change  # `always` will be the setting once code changes slow down
